server:
  port: 8084
fraud-check:
  grpc:
    address: static://localhost:9091
spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: platform
    password: platform
    hikari:
      pool-name: PaymentServiceHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest

  

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics